Branch1
MartinPetrakiev/c_sharp_loops pull request #1
Opened 2023-08-17 16:12 UTC by MartinPetrakiev

2023-08-17 16:39 UTC, mvlt requested changes

2023-08-17 16:39 UTC, mvlt commented on GCD/Program.cs
> +            string[] numbersArray = input.Split(' ');
Why this happens in this function

2023-08-17 16:39 UTC, mvlt commented on GCD/Program.cs
> +            for (int i = 1; i <= biggestNumber; i++)
Euclidean algorithm is not used

2023-08-17 17:26 UTC, mvlt commented on Trailing_0_in_N!/Program.cs
> +
the solution will work properly not sure if it will 0.1 sec for N = 100000. Try to find some logic between factorial and trailing zeros and optimize the solution. 
https://www.mymathtables.com/numbers/100-factorial-tables-chart.html

2023-08-17 19:01 UTC, mvlt commented on Catalan_Numbers/Program.cs
> +                fact2N *= (BigInteger)k;
Try optimizing loop's count. If limits for BigInteger input is not covered you need to change the solution.

2023-08-18 10:48 UTC, MartinPetrakiev commented on Catalan_Numbers/Program.cs
> +                fact2N *= (BigInteger)k;
Updated
(https://github.com/MartinPetrakiev/c_sharp_loops/pull/1/commits/d91eab67f107cabca675dc7630f34dee50d3cf0e)

2023-08-18 10:48 UTC, MartinPetrakiev commented on Spiral_Matrix/Program.cs
> +Description
Updated in
(https://github.com/MartinPetrakiev/c_sharp_loops/pull/1/commits/152b1e75e4ba84b125946c9e395a407e23d4b07f)

2023-08-18 10:49 UTC, MartinPetrakiev commented on Trailing_0_in_N!/Program.cs
> +
Updated in
[152b1e7](https://github.com/MartinPetrakiev/c_sharp_loops/pull/1/commits/152b1e75e4ba84b125946c9e395a407e23d4b07f)

2023-08-30 18:42 UTC, mvlt approved these changes

2023-08-30 22:29 UTC, merged